name: fake_news_detection

on:
  workflow_dispatch:

jobs:
  download-dataset-processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Install Kaggle API
        run: pip install kaggle
      - name: Download dataset from Kaggle
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_N }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_K }}
        run: |
          kaggle datasets download -d clmentbisaillon/fake-and-real-news-dataset
          unzip fake-and-real-news-dataset.zip
      - name: Upload CSV files as artifact - 1
        uses: actions/upload-artifact@v3.1.2
        with:
          name: csv-files
          path: |
            *.csv
      - name: Install Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r req.txt
      - name: Preprocessing
        run: |
          python preprocess.py
      - name: Upload a Build Artifact - 2
        uses: actions/upload-artifact@v3.1.2
        with:
          name: preprocess_file
          path: |
            merged.csv
            main_data.csv
            main_data_new.csv
          
  Feature-Extraction:
    needs: download-dataset-processing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Download artifact - 1
        uses: actions/download-artifact@v3.0.2
        with:
          name: preprocess_file
      - name: Install Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r req.txt
      - name: Feature
        run: |
          python feature.py
      - name: Upload a Build Artifact - 3
        uses: actions/upload-artifact@v3.1.2
        with:
          name: feature
          path: |
            vectorizer_old.pickle
            features_old.pickle
            vectorizer_new.pickle
            features_new.pickle

  Learn-and-save-models:
    needs: Feature-Extraction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Download artifact - 2
        uses: actions/download-artifact@v3.0.2
        with:
          name: preprocess_file
      - name: Download artifact - 3
        uses: actions/download-artifact@v3.0.2
        with:
          name: feature
      - name: Install Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r req.txt
      - name: Learn and Save
        run: |
          python learn_and_save.py
      - name: Upload a Build Artifact - 4
        uses: actions/upload-artifact@v3.1.2
        with:
          name: save_models_info_metrics
          path: |
            info_new.txt
            info_old.txt
            model_lr_old.pickle
            model_lr_new.pickle
      - name: Commit and Push changes - 1
        run: |
         git config --global user.email "zhilin.valentin.72@gmail.com"
         git config --global user.name "Valentin"
         rm -rf model_repo && mkdir model_repo
         cp ${{ github.workspace }}/info_new.txt model_repo/
         git add model_repo/
         git commit -m "update"
         git push

  Test_models:
    needs: Learn-and-save-models
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Download artifact - 4
        uses: actions/download-artifact@v3.0.2
        with:
          name: preprocess_file
      - name: Download artifact - 5
        uses: actions/download-artifact@v3.0.2
        with:
          name: feature
      - name: Download artifact - 5
        uses: actions/download-artifact@v3.0.2
        with:
          name: save_models_info_metrics
      - name: Install Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r req.txt
      - name: Learn and Save
        run: |
          python test_models.py
      - name: Upload a Build Artifact - 4
        uses: actions/upload-artifact@v3.1.2
        with:
          name: save_result_predict
          path: |
           result.txt
           result_new.txt
      - name: Commit and Push changes - 1
        run: |
         git config --global user.email "zhilin.valentin.72@gmail.com"
         git config --global user.name "Valentin"
         git pull
         rm -rf results && mkdir results
         cp ${{ github.workspace }}/result.txt results/
         cp ${{ github.workspace }}/result_new.txt results/
         git add result/
         git commit -m "update"
         git push
