name: Main

on:
  workflow_dispatch:

jobs:
  download_dataset:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Kaggle API
      run: pip install kaggle
    - name: Download dataset from Kaggle
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_N }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_K }}
      run: |
        kaggle datasets download -d clmentbisaillon/fake-and-real-news-dataset -p data/      
    - name: Upload to Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-dataset
        path: data
  
