name: Download Dataset from Kaggle

on:
  workflow_dispatch:

jobs:
  download-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Install Kaggle API
        run: pip install kaggle
      - name: Download dataset from Kaggle
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_N }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_K }}
        run: |
          mkdir -p data
          kaggle datasets download -d clmentbisaillon/fake-and-real-news-dataset -p data/
      - name: Unzip dataset
        run: unzip -qo data/*.zip -d data/
      - name: Filter CSV files
        run: |
          mv ./data/*.csv ./
          rm -rf ./data
      
      - name: Upload CSV files as artifact - 1
        uses: actions/upload-artifact@v3.1.2
        with:
          name: csv-files
          path: |
            *.csv
      - name: Install Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r req.txt
      - name: Test data
        run: |
          python test.py
      - name: Upload a Build Artifact - 2
        uses: actions/upload-artifact@v3.1.2
        with:
          name: csv_fi
          path: Test.csv
      - name: Tester data
        run: |
          python tester.py
      - name: Upload a Build Artifact - 3
        uses: actions/upload-artifact@v3.1.2
        with:
          name: new_csv_fi
          path: Tester.csv
